dim text, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect("gretxp", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT EHNR,  EHTEXT FROM [Tabelle1$] where ehunr = 0 order by EHNR", text, ErrorMsg)

if ( rc < 0 ) then

MessageBox( "Query Error", ErrorMsg, 4, 1)

else

PanelFieldSetProp ("EHCD", 5, text) 
PanelUpdateEnable(2)

endif