
dim text, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT vavnr, vaname concat ' ' concat digits(vavnr) from gradrp  order by vaname concat ' ' concat digits(vavnr)", text, ErrorMsg)

if ( rc < 0 ) then

MessageBox( "Query Error", ErrorMsg, 4, 1)

else

PanelFieldSetProp ("verlag", 5, text) 

PanelUpdateEnable(2)

endif