dim text, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT digits(EHNR) concat digits(ehunr), DIGITS(EHNR) concat digits(ehunr) concat ' - 'concat EHTEXT FROM GRETXP order by  EHNR", text, ErrorMsg)

if ( rc < 0 ) then

MessageBox( "Query Error", ErrorMsg, 4, 1)

else

PanelFieldSetProp ("EHCD", 5, text) 


PanelUpdateEnable(2)

endif