rem **Füllen Combo-Box  aus GRVERP **

dim text, ErrorMsg as String
dim rc as Integer




rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT logsspednr, digits(logsspednr) concat ' ' concat logsfirm1 FROM grlogspedp  order by digits(logsspednr)", text, ErrorMsg)
PanelFieldSetProp ("logsvsped", 5, text) 


PanelUpdateEnable(2)