dim text, ErrorMsg as String
dim rc as Integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif


rem **bevorzugte Sprache
rc = EzSQLQuery("SELECT laland, digits(laland) concat ' - ' concat LANAME FROM GRLANP order by laland", text, ErrorMsg)

if ( rc < 0 ) then
MessageBox( "Query Error", ErrorMsg, 4, 1)
else
PanelFieldSetProp ("kdnat", 5, text) 
PanelUpdateEnable(2)
endif