
dim text, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT vavnr, vaname from gradrp where vaname not like '*%' order by vaname", text, ErrorMsg)
PanelFieldSetProp ("f1vlg", 5, text) 

PanelUpdateEnable(2)

ScriptCall("c_fil")

HostScreenSendKey("F5")