rem **Füllen Combo-Box  aus GRGARP **

dim text, ErrorMsg as String
dim rc as Integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT DIGITS(kdgart) concat DIGITS(kdgaug), DIGITS(kdgart) concat DIGITS(kdgaug) concat ' - 'concat kdgtxt FROM GRGARP order by DIGITS(kdgart) concat DIGITS(kdgaug)", text, ErrorMsg)


PanelFieldSetProp ("gagu", 5, text) 
PanelUpdateEnable(2)