
dim text, ErrorMsg as String
dim rc as Integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT  digits(jahr) concat digits(monat) FROM grkalp where tag = 1  order by digits(jahr) concat digits(monat) ", text, ErrorMsg)

if ( rc < 0 ) then

MessageBox( "Query Error", ErrorMsg, 4, 1)

else

PanelFieldSetProp ("yyjjmm", 5, text) 

PanelUpdateEnable(2)

endif