dim text, ErrorMsg as String
dim rc as Integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif



rem **ZENTRALEN AUS GRTSSP

rc = EzSQLQuery("SELECT TSGES, TSNAME FROM GRTSSP order by TSNAME", text, ErrorMsg)

if ( rc < 0 ) then
MessageBox( "Query Error", ErrorMsg, 4, 1)
else
PanelFieldSetProp ("KDTANK", 5, text) 
PanelUpdateEnable(2)
endif