dim text, xxobj, ErrorMsg,sqlstmd as String
dim rc as Integer
dim con_table as integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

PanelFieldGetData("objnr", xxobj, 0)
sqlstmd = "select pzmanr, pzobjn concat ' ' concat prpbez from grflprp inner join grflpzp  on prpnr = pzpnr where pzobjn = " + xxobj
rc = EzSQLQuery(sqlstmd, text, ErrorMsg)
PanelFieldSetProp ("xxprae", 5, text) 


PanelUpdateEnable(2)