dim text, ErrorMsg as String
dim rc as Integer
Global Filiale as string

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT adkey, digits(adkey) concat ' ' concat adtext FROM GRADTP where adaktiv <> 'U' order by adkey", text, ErrorMsg)

if ( rc < 0 ) then
MessageBox( "Query Error", ErrorMsg, 4, 1)
else
PanelFieldSetProp ("adkey", 5, text) 
endif

PanelUpdateEnable(2)