dim text, xxdat, sqlstmd, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

HostFieldGetData("WDDAT", xxdat)

sqlstmd = "SELECT grffeld, grffeld concat ' ' concat grffeltext FROM grkdgrfp where  grfdatei = " +"'"+ xxdat +"'" + " order by grffeld"

rc = EzSQLQuery(sqlstmd, text, ErrorMsg)
PanelFieldSetProp ("box2", 5, text)

PanelUpdateEnable(2)