dim text, ErrorMsg as String
dim rc as Integer
global filiale as string

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT substr(vlvlkz, 1, 6),  vlvbez concat ' ' concat substr(vlvlkz, 1, 6) FROM  GRVTLL3", text, ErrorMsg)

if ( rc < 0 ) then
MessageBox( "Query Error", ErrorMsg, 4, 1)
else
PanelFieldSetProp ("xxvtl", 5, text) 
PanelUpdateEnable(2)
endif

ScriptCall("c_fil")