dim text, ErrorMsg,sqlstmd as String
dim rc as Integer
dim con_table as integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rem *** Abgangsgrund
sqlstmd = "SELECT abnr, abnr concat ' ' concat abtext FROM grabgp order by abnr"
rc = EzSQLQuery(sqlstmd, text, ErrorMsg)

PanelFieldSetProp ("abgg1", 5, text) 

PanelUpdateEnable(2)