dim text, ErrorMsg as String
dim rc as Integer

rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif


rem ** VERLAGSSTAMM bereitsttellen **
rc = EzSQLQuery("SELECT digits(VAVNR), DIGITS(VAVNR) concat ' - 'concat VANAME FROM GRADRP order by VANAME", text, ErrorMsg)

PanelFieldSetProp ("S1VNR",  5, text) 
PanelUpdateEnable(2)