rem **Füllen Combo-Box  aus GRLTYP **

dim text, ErrorMsg as String
dim rc as Integer


rc = EzSQLConnect(@"@&ODBC@", "", "", ErrorMsg)
if ( rc < 0 ) then
MessageBox( "Connect Error", ErrorMsg, 4, 1)
endif

rc = EzSQLQuery("SELECT LYTYP, lytyp concat ' - ' concat LYTEXT FROM GRLTYP", text, ErrorMsg)

if ( rc < 0 ) then

MessageBox( "Query Error", ErrorMsg, 4, 1)

else

PanelFieldSetProp ("C_LTYP", 5, text) 
PanelUpdateEnable(2)

endif

ScriptCall("c_fil")