dim xxstrasse,xxplz, xxort, xxname as string
PanelFieldGetData("sstrasse", xxstrasse)
if xxstrasse <> "" then
xxname = "&" + xxstrasse
PanelFieldPutData("kdknam", 0, xxname)
endif
PanelFieldGetData("splz", xxplz)
if xxplz <> "" then
xxname = "#" + xxplz
PanelFieldPutData("kdknam", 0, xxname)
endif
PanelFieldGetData("sort", xxort)
if xxort <> "" then
xxname = "?" + xxort
PanelFieldPutData("kdknam", 0, xxname)
endif
HostScreenSendKey("enter")
PanelButtonClick("close")